# Generated by Django 3.0.6 on 2020-06-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField()),
                ('country_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=255)),
                ('who_region', models.CharField(max_length=255)),
                ('new_cases', models.IntegerField()),
                ('cumulative_cases', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('cumulative_deaths', models.IntegerField()),
            ],
        ),
    ]
